name = "hakodate"
main = "src/index.ts"
compatibility_date = "2025-01-26"
compatibility_flags = ["nodejs_compat_v2"]

[assets]
directory = "./public"

[browser]
binding = "BROWSER"
remote = true

[triggers]
crons = ["0 1-13 * * *"]
# デバッグ用: 5分ごとに実行
# crons = ["*/5 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "hakodate"
database_id = "549afc23-e0ed-4446-8190-cbd055db06be"

[observability]
[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = false
